// @ts-check
import { defineConfig } from 'astro/config';

import { DEFAULT_LOCALE, LOCALES } from './src/i18n/config.ts';

/**
 * Deployment target.
 *
 * GitHub Pages serves project sites from a sub-path, so `base` must match the
 * repository name. When a custom domain is added later, set `SITE` to that
 * domain and `BASE_PATH` to '/' — nothing else needs to change.
 */
const site = process.env.SITE ?? 'https://timbencker.github.io';
const base = process.env.BASE_PATH ?? '/celine-bencker-website';

export default defineConfig({
  site,
  base,

  // GitHub Pages has no server: every route is pre-rendered to a file.
  output: 'static',

  // Language lives in the URL, never in a cookie. Both locales are prefixed so
  // every page is linkable and citable in each language.
  //
  // NOTE: `routing.redirectToDefaultLocale` is deliberately NOT set — it
  // requires `output: 'server'`. The root redirect is handled by
  // `src/pages/index.astro` instead, which works on static hosting.
  i18n: {
    locales: [...LOCALES],
    defaultLocale: DEFAULT_LOCALE,
    routing: {
      prefixDefaultLocale: true,
    },
  },

  // The sitemap is generated by `src/pages/sitemap.xml.ts` rather than
  // @astrojs/sitemap, which cannot express per-locale slugs. See that file.
});
